### ISSUE TITLE
Error running Git: Tag and Push

### ISSUE THREAD

**Issue by woter1832** [patrickfnielsen/vscode-git-tag-push#4]
Hi,

I get the following error when trying to use your extension.

![image](https://user-images.githubusercontent.com/68354513/144328134-ea86eaf8-ad35-4da0-acba-dc0407531fb4.png)

Using the latest version of VSCode for Windows.

Thanks

**Comment by patrickfnielsen** [comment]
I'll try and see if I can reproduce the error this weekend

**Comment by patrickfnielsen** [comment]
Sorry for the very late response on this, but I've not be able to reproduce this on Windows.

If you still want to use it, could you try and get the logs from:
cmd-shift-p (or ctrl-shift-p) -> Developer Show Logs -> Extension Host

Thanks,
